services:
  db:
    image: pgvector/pgvector:pg16
    container_name: epistemiq-db
    environment:
      POSTGRES_USER: epistemiq
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: epistemiq_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
